### ISSUE TITLE
Some plist files are not shown properly

### ISSUE THREAD

**Issue by nasht00** [atom/language-property-list#3]
Some plist files cannot be opened in atom.
Example: ~/Library/Preferences/com.apple.LaunchServices.plist

It looks like this:
![screen shot 2015-08-25 at 10 59 28 am](https://cloud.githubusercontent.com/assets/329834/9461611/73ec041a-4b18-11e5-94a6-9fc2b62605c6.png)

Yet in TextWrangler it looks like:
![screen shot 2015-08-25 at 11 01 10 am](https://cloud.githubusercontent.com/assets/329834/9461655/a1842466-4b18-11e5-8cb2-54b0f3dd9735.png)

**Comment by nasht00** [comment]
Actually it looks strange in VIM as well.
<img width="548" alt="screen shot 2015-08-25 at 11 06 49 am" src="https://cloud.githubusercontent.com/assets/329834/9461756/699668ce-4b19-11e5-822f-3feb592dba49.png">

Sublime:
<img width="381" alt="screen shot 2015-08-25 at 11 06 19 am" src="https://cloud.githubusercontent.com/assets/329834/9461749/5c649cd4-4b19-11e5-8a6d-d42454cf4936.png">

I would attach the plist file here, but not sure how.

**Comment by nasht00** [comment]
cat:

<img width="545" alt="screen shot 2015-08-25 at 11 08 18 am" src="https://cloud.githubusercontent.com/assets/329834/9461788/a291a83c-4b19-11e5-86f9-e7dbef9a6a73.png">

**Comment by 50Wliu** [comment]
@nasht00 you can save it as a [Gist](https://gist.github.com/) and paste the link here.  Weird how only TextWrangler shows it correctly.

**Comment by BigxMac** [comment]
Apparently you can convert the file to XML using the <code>plutil</code> terminal command like so
<code>plutil -convert xml1 file.plist</code>

**Comment by nasht00** [comment]
@50Wliu I can paste it as gist but wouldn't that get rid of the problematic encoding?

**Comment by pudquick** [comment]
This is a binary plist, mentioned by Apple in several documentation locations.

Only source code example from Apple I'm aware of is: http://www.gnu-darwin.org/www001/src/DarwinSourceArchive/expanded/CF/CF-299/Parsing.subproj/CFBinaryPList.c

But applications like TextWrangler / BBEdit likely just use native Apple APIs for loading the binary file and then converting it to a XML representation behind the scenes, like:

```objective-c
[NSPropertyListSerialization dataFromPropertyList:plistDict format:NSPropertyListXMLFormat_v1_0 errorDescription:&error]```

There are several opensource projects out there that implement binary plist parsing functionality in various language (perl, python, etc.)

**Comment by danielbayley** [comment]
You can now download the [plist-converter](https://atom.io/packages/plist-converter) package which handles automatic conversion from binary to XML and back on open/close of `.plist` files.

**Comment by 50Wliu** [comment]
Closing as handling these types of plists is out of the scope of language-property-list, as explained in https://github.com/atom/language-property-list/pull/4#issuecomment-155238069.
