### ISSUE TITLE
'Install' button not present

### ISSUE THREAD

**Issue by dudeinthemirror** [atom/language-property-list#8]
`CMD-,` --> Install --> `language-property-list` --> Search

![screen shot 2016-07-05 at 4 43 16 pm](https://cloud.githubusercontent.com/assets/981638/16603282/9b95d82e-42cf-11e6-9033-5a47ab3a326b.png)

Install button is not present, can't install the package.

Atom version 1.8.0

**Comment by 50Wliu** [comment]
This is because it's already installed.
